apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../base/calendar

namespace: preprod

images:
- name: glow/calendar
  newName:  312395729448.dkr.ecr.us-east-2.amazonaws.com/dev-repository/calendar
  newTag: latest
