apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendportal
  namespace: default
  labels:
    app: backendportal
spec:
  replicas: 1 #CHANGE
  #minReadySeconds: 60
  selector:
    matchLabels:
      app: backendportal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backendportal
    spec:
      restartPolicy: Always
      #terminationGracePeriodSeconds: 30
      containers:
        - name: backendportal
          image: 312395729448.dkr.ecr.us-east-2.amazonaws.com/dev-repository/backenportal:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: env.namespace
              value: default
          resources: #CHANGE
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m #400m
              memory: 1024Mi #256Mi

---
kind: Service
apiVersion: v1
metadata:
  name: backendportal
  labels:
    app: backendportal
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /backendportal/swagger-ui.html
spec:
  selector:
    app: backendportal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30037
  type: NodePort
