apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../base/backendportal

namespace: preprod

images:
- name: glow/backendportal
  newImage: 312395729448.dkr.ecr.us-east-2.amazonaws.com/dev-repository/backendportal
  newTag: latest
