apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../base/central-config-server

namespace: preprod

images:
- name: glow/central-config-server
  newImage: 312395729448.dkr.ecr.us-east-2.amazonaws.com/dev-repository/central-config-server
  newTag: latest
